name: Fork OSS

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnigh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone the repo
        run: ${repository}

      - name: Add 'upstream' repo to list of remotes
        run: git remote add upstream ${repository}

      - name: Verify the new remote named 'upstream'
        run: git remote -v

      - name: Fetch from upstream remote
        run: git fetch upstream

      - name: View all branches, including those from upstream
        run: git branch -va

      - name: Checkout your master branch and merge upstream
        run: git checkout master && git merge upstream/master

    env:
      CI: true
      repository: https://github.com/kubernetes-sigs/kubespray.git