name: Fork OSS

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'kubernetes-sigs/kubespray'

    - name: Git-remote-add
      run: git remote add kubespray https://github.com/kubernetes-sigs/kubespray.git

    - name: Git-fetch-all
      run: git fetch --all

    - name: Git-clone
      run: |
        git clone https://github.com/kubernetes-sigs/kubespray.git
        ls -al
    
    env:
      CI: true
      repository: "https://github.com/kubernetes-sigs/kubespray.git"
